const ITEM_COLOR = 0x00a8ff;
const ITEM_COMPONENT_PREFIX = "item:";
const BUY_BUTTON_PREFIX = `${ITEM_COMPONENT_PREFIX}buy:`;
const PAGE_BUTTON_PREFIX = `${ITEM_COMPONENT_PREFIX}page:`;
const BUTTON_CONTEXT_TTL_MS = 15 * 60 * 1000;
const ITEMS_PER_PAGE = 7;

module.exports = {
  BUTTON_CONTEXT_TTL_MS,
  BUY_BUTTON_PREFIX,
  ITEM_COLOR,
  ITEM_COMPONENT_PREFIX,
  ITEMS_PER_PAGE,
  PAGE_BUTTON_PREFIX,
};
