const CHARACTER_COLORS = {
  neutral: 0xf2f4f8,
  detail: 0xc9ced8,
  warning: 0x8d94a0,
};

const MAX_ACTIVE_CHARACTERS = 3;
const DEFAULT_STATISTICS_VERSION = 1;
const CHARACTER_COMPONENT_PREFIX = "character";
const CHARACTER_CREATE_MODAL_PREFIX = `${CHARACTER_COMPONENT_PREFIX}:create`;
const CHARACTER_DELETE_MODAL_PREFIX = `${CHARACTER_COMPONENT_PREFIX}:delete`;
const CHARACTER_EDIT_MODAL_PREFIX = `${CHARACTER_COMPONENT_PREFIX}:edit:modal`;
const CHARACTER_EDIT_MODAL_TTL_MS = 15 * 60 * 1000;
const CHARACTER_LIST_BUTTON_PREFIX = `${CHARACTER_COMPONENT_PREFIX}:list:button`;
const CHARACTER_LIST_CONTEXT_TTL_MS = 60 * 60 * 1000;
const CHARACTER_LIST_DIRECTIONS = {
  next: "next",
  previous: "previous",
};
const CHARACTER_VIEW_BUTTON_PREFIX = `${CHARACTER_COMPONENT_PREFIX}:view`;
const CHARACTER_VIEW_CONTEXT_TTL_MS = 60 * 60 * 1000;
const CHARACTER_VIEW_PANELS = {
  economy: "economy",
  information: "information",
  profile: "profile",
  statistics: "statistics",
};

module.exports = {
  CHARACTER_COLORS,
  CHARACTER_COMPONENT_PREFIX,
  CHARACTER_CREATE_MODAL_PREFIX,
  CHARACTER_DELETE_MODAL_PREFIX,
  CHARACTER_EDIT_MODAL_PREFIX,
  CHARACTER_EDIT_MODAL_TTL_MS,
  CHARACTER_LIST_BUTTON_PREFIX,
  CHARACTER_LIST_CONTEXT_TTL_MS,
  CHARACTER_LIST_DIRECTIONS,
  CHARACTER_VIEW_BUTTON_PREFIX,
  CHARACTER_VIEW_CONTEXT_TTL_MS,
  CHARACTER_VIEW_PANELS,
  DEFAULT_STATISTICS_VERSION,
  MAX_ACTIVE_CHARACTERS,
};
